Import('*')

env.Append(LINKFLAGS = Split("-pthread"))
env.Append(CCFLAGS = Split("-O -Wall"))
env.Append(LIBS = Split('boost_program_options boost_system'))

env.Program('#/' + target, Glob('*.cpp'))
